[env:esportable32]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
board_build.partitions = esportable32_partitions.csv
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    bblanchon/ArduinoJson @ ^7.0.0
